# Generated by Django 5.2.8 on 2025-12-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cached_data', models.JSONField(help_text='Serialized question data')),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Cache',
                'verbose_name_plural': 'Question Caches',
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='TimedQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Quiz duration in minutes')),
                ('questions_count', models.IntegerField(default=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timed Quiz Session',
                'verbose_name_plural': 'Timed Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=10)),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('adaptive', 'Adaptive')], default='adaptive', max_length=20)),
                ('enable_sound', models.BooleanField(default=True)),
                ('enable_animations', models.BooleanField(default=True)),
                ('show_explanations', models.BooleanField(default=True)),
                ('auto_next_question', models.BooleanField(default=False)),
                ('questions_per_session', models.IntegerField(default=20)),
                ('enable_keyboard_shortcuts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], db_index=True, max_length=20)),
                ('period_start', models.DateField()),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField()),
                ('questions_answered', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'rank'], name='quiz_leader_period_66a5b3_idx')],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('average_time_per_question', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('domains_covered', models.JSONField(default=dict, help_text='Domain-wise performance')),
                ('difficulty_breakdown', models.JSONField(default=dict, help_text='Performance by difficulty')),
                ('streak_count', models.IntegerField(default=0)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback about the question')),
                ('is_too_easy', models.BooleanField(default=False)),
                ('is_too_hard', models.BooleanField(default=False)),
                ('is_unclear', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Rating',
                'verbose_name_plural': 'Question Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
