# Generated by Django 5.2.8 on 2025-12-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Draft', max_length=200)),
                ('original_text', models.TextField()),
                ('transformed_text', models.TextField(blank=True)),
                ('transformation_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Draft',
                'verbose_name_plural': 'Saved Drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TextComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('transformed_text', models.TextField()),
                ('transformation_type', models.CharField(max_length=50)),
                ('differences_highlighted', models.JSONField(default=dict, help_text='Highlighted differences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Comparison',
                'verbose_name_plural': 'Text Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('transformed_text', models.TextField()),
                ('transformation_type', models.CharField(max_length=50)),
                ('character_count_before', models.IntegerField()),
                ('character_count_after', models.IntegerField()),
                ('word_count_before', models.IntegerField()),
                ('word_count_after', models.IntegerField()),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transformation History',
                'verbose_name_plural': 'Transformation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWritingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transformations', models.IntegerField(default=0)),
                ('total_characters_processed', models.BigIntegerField(default=0)),
                ('total_words_processed', models.BigIntegerField(default=0)),
                ('favorite_transformation', models.CharField(blank=True, max_length=50)),
                ('total_drafts_saved', models.IntegerField(default=0)),
                ('total_templates_used', models.IntegerField(default=0)),
                ('average_processing_time_ms', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Writing Stats',
                'verbose_name_plural': 'User Writing Stats',
            },
        ),
        migrations.CreateModel(
            name='WritingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('email', 'Email'), ('letter', 'Letter'), ('essay', 'Essay'), ('report', 'Report'), ('creative', 'Creative Writing'), ('business', 'Business'), ('academic', 'Academic'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('template_text', models.TextField()),
                ('placeholder_fields', models.JSONField(default=list, help_text='List of placeholder fields')),
                ('is_public', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writing Template',
                'verbose_name_plural': 'Writing Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
